### ISSUE TITLE
Build cannot resolve dependency

### ISSUE THREAD

**Issue by tzaeschke** [antzGames/ode4j-GWT-Compatible-libGDX#3]
I just tried to build the project with `gradle build` and `gradle html:superDev`. In both cases it fails with something like:
```
$ gradle build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ode4j-GWT-Compatible-libGDX'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:7.0.4.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:7.0.4.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/7.0.4/gradle-7.0.4.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
      > Could not resolve com.android.tools.build:gradle:7.0.4.
         > Could not get resource 'https://s01.oss.sonatype.org/com/android/tools/build/gradle/7.0.4/gradle-7.0.4.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
      > Could not resolve com.android.tools.build:gradle:7.0.4.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.0.4/gradle-7.0.4.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
      > Could not resolve com.android.tools.build:gradle:7.0.4.
         > Could not get resource 'https://plugins.gradle.org/m2/com/android/tools/build/gradle/7.0.4/gradle-7.0.4.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
      > Could not resolve com.android.tools.build:gradle:7.0.4.
         > Could not get resource 'https://oss.sonatype.org/content/repositories/snapshots/com/android/tools/build/gradle/7.0.4/gradle-7.0.4.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
      > Could not resolve com.android.tools.build:gradle:7.0.4.
         > Could not get resource 'https://s01.oss.sonatype.org/content/repositories/snapshots/com/android/tools/build/gradle/7.0.4/gradle-7.0.4.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
   > Could not resolve org.wisepersist:gwt-gradle-plugin:1.1.19.
     Required by:
         project :
      > Could not resolve org.wisepersist:gwt-gradle-plugin:1.1.19.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/wisepersist/gwt-gradle-plugin/1.1.19/gwt-gradle-plugin-1.1.19.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
      > Could not resolve org.wisepersist:gwt-gradle-plugin:1.1.19.
         > Could not get resource 'https://s01.oss.sonatype.org/org/wisepersist/gwt-gradle-plugin/1.1.19/gwt-gradle-plugin-1.1.19.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
      > Could not resolve org.wisepersist:gwt-gradle-plugin:1.1.19.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/org/wisepersist/gwt-gradle-plugin/1.1.19/gwt-gradle-plugin-1.1.19.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
      > Could not resolve org.wisepersist:gwt-gradle-plugin:1.1.19.
         > Could not get resource 'https://plugins.gradle.org/m2/org/wisepersist/gwt-gradle-plugin/1.1.19/gwt-gradle-plugin-1.1.19.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
      > Could not resolve org.wisepersist:gwt-gradle-plugin:1.1.19.
         > Could not get resource 'https://oss.sonatype.org/content/repositories/snapshots/org/wisepersist/gwt-gradle-plugin/1.1.19/gwt-gradle-plugin-1.1.19.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
      > Could not resolve org.wisepersist:gwt-gradle-plugin:1.1.19.
         > Could not get resource 'https://s01.oss.sonatype.org/content/repositories/snapshots/org/wisepersist/gwt-gradle-plugin/1.1.19/gwt-gradle-plugin-1.1.19.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 228ms

```

My gradle version:
```
$ gradle --version

------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.1 (Private Build 16.0.1+9-Ubuntu-120.04)
OS:           Linux 5.19.0-38-generic amd64

```

**Comment by antzGames** [comment]
Are you using Android Studio or IntelliJ as your IDE?  libGDX deploys to 4 platforms Desktop, Android, iOS and GWT so its best you use those.

Also if you use these IDEs you don't need superDev (which is slow because its a debugging platform).  You create a `dist` gradle target and then you can open with your web browser as Intellij has a built in web browser.

`In the README.md`
Use IntelliJ or Android Studio as your IDE for minimal issues building. You may have to your tweak the gradle version/plugin. I used Gradle Version 7.6 and Android Gradle Plugin Version 7.0.4

**Comment by tzaeschke** [comment]
I was using just the Linux console with `gradle build`. Using `gradle dist` on the console gives me similar errors as above.

I also tried IntelliJ. I am not sure how to do a `gradle dist`in Intellij. In the IntelliJ Gradle window I did find "lwjgl->Tasks->application->run", this worked and I could run the test app.

What I am really trying to do is debug the problem you mentioned in the ode4j Discord channel (I am the ode4j maintainer). I assume there is a very specific alignment between a cylinder and a trimesh that causes the problem, but I could not reverse engineer this mathematically. I could not reproduce yet so I am trying to reproduce it with your project.

**Comment by antzGames** [comment]
Hey Til. So dont run anything command line always use the Gradle GUI.  

To run desktop (which is way easier follow this image:

![image](https://user-images.githubusercontent.com/10563814/235899710-69fa93de-3e89-44ed-ae5b-089615411ea6.png)

For GWT (HTML) its more complicated as you have to run the HTML on a webserver.  IntelliJ has one built in and the screen below shows you how:

![image](https://user-images.githubusercontent.com/10563814/235898501-7b05d938-f9be-4814-b3d7-28e5966eb8f4.png)

You can run SuperDev and the logs will point you to http://localhost:8080 (not shown).

**Comment by antzGames** [comment]
So you have to make sure you have a JDK installed that supports the correct gradle version.  The JDK version for gradle is independent of the JDK you use to compile your program.  I used JDK 11 for Gradle V7.6.  Also libGDX itself needs a minimum of Java 8 (1.8).

![image](https://user-images.githubusercontent.com/10563814/235902486-b586adb2-dbeb-4ced-9b76-3f6ef83fd18c.png)

**Comment by antzGames** [comment]
> I assume there is a very specific alignment between a cylinder and a trimesh that causes the problem, but I could not reverse engineer this mathematically. I could not reproduce yet so I am trying to reproduce it with your project.

So I had many problems with cylinder.  It does not rotate correctly.  It rotates on its flat sides vs. the cylinder sides.  I checked the AABB bounding box and it is not an alignment difference between the rendering and physics engine.  In addition it does not seem like ODE has a CONE primitive.

**Comment by tzaeschke** [comment]
### Weird cylinder behavior
I suspect the problem with the weirdly rolling cylinders is that the visualization uses different axes than the physics engine. You can see it more clearly when you make the cylinders a bit more asymmetric, e.g. by setting `height=2`. You can see that some roll over the long end. I also never saw this rolling behavior in any of the ode4j demos. The cylinder axis is by default the z-axis in ode4j (unless I am severely mistaken).

### Cylinder collision causing exception when position is not set
I have more or less tracked down the Exception that is thrown when colliding cylinders. It seems to happen when their centers lie directly on the axis of the cylinder. I cannot fully reproduce it yet but I can see that the this situation leads to the contact normal being `{NaN, NaN, NaN}` which causes all kinds of problems.

**Comment by antzGames** [comment]
> I suspect the problem with the weirdly rolling cylinders is that the visualization uses different axes than the physics engine. You can see it more clearly when you make the cylinders a bit more asymmetric, e.g. by setting `height=2`. You can see that some roll over the long end. I also never saw this rolling behavior in any of the ode4j demos. The cylinder axis is by default the z-axis in ode4j (unless I am severely mistaken).

I thought this was it too.  The red AABB boxes are coming from ode4j, and they look aligned to the size of the capsule being rendered in the video below.  BTW both mass and geom for cylinder have a LENGTH parameter, not height.  You can set the axis direction on the mass of a cylinder.  So the only other thing it could be is that if you set the rotation for both body and geom to be the same, does linking the body (`gemo.setBody()`) keep the rotation the same?

https://user-images.githubusercontent.com/10563814/236220076-12eb957b-8cac-4039-af6b-49b5f3e88660.mp4

**Comment by antzGames** [comment]
> ### Cylinder collision causing exception when position is not set
> I have more or less tracked down the Exception that is thrown when colliding cylinders. It seems to happen when their centers lie directly on the axis of the cylinder. I cannot fully reproduce it yet but I can see that the this situation leads to the contact normal being `{NaN, NaN, NaN}` which causes all kinds of problems.

This is great.  BTW, so my code change Double.doubleToRawLongBits() is not supported in GWT.  This method handles NaN which is not supported in WGT (i,e, Javascript cannot support this).  Something I need to keep in mind.

**Comment by antzGames** [comment]
OK I fixed the cylinder rolling problem.  So libGDX and ode4j create cylinders on different axis.  I have to rotate them when I get the physics rotation and map them to the render rotation.    

https://user-images.githubusercontent.com/10563814/236243586-6f800507-3ef9-4ea5-860c-ee6f46c1247e.mp4

**Comment by tzaeschke** [comment]
> OK I fixed the cylinder rolling problem. So libGDX and ode4j create cylinders on different axis. I have to rotate them when I get the physics rotation and map them to the render rotation. My player cylinder was also incorrect.

Nice :-)
Anyway, I will close this, building and execution works fine when using IntelliJ.

**Comment by antzGames** [comment]
I will be pushing new code soon.  It fixes a lot of stuff.  I am glad you can build now.
